NebraLtd/hm-pktfwd

Dockerfile

Changed to ARMV5 base in preperation for light hotspots.
So far tested fine on testnet.

Armv6 / v5

---

Dockerfile
files/checksx1302.py
files/configurePktFwd.py

Swap to Balena Raspbian Base which is compatible with Pi Zero / Pi 1 SOC in preperation for Light Hotspots.

New Raspbian Base

---

Dockerfile

Revert "Change to minimal python"

---

Dockerfile
files/checksx1302.py
files/configurePktFwd.py

Revert "New Raspbian Base"

---

.github/workflows/shellcheck.yml

add shellcheck test
Closes: #17 
Signed-off-by: Aaron Shaw <shawaj@gmail.com>

test: add shellcheck

---

files/configurePktFwd.py

comments were the wrong way round

fix: correct comments

---

Dockerfile

* Removes pinning of packages (as this is likely to break in the future)
* Tweaks cleanup process in final container

Removes pinning and tweaks cleanup in final container

---

lora_templates_sx1301/AU-global_conf.json
lora_templates_sx1302/AU-global_conf.json

Revert AU915 changes
**Why**
**How**
**References**
Closes: #48

Revert AU915 changes

---

requirements.txt

**Why**
bump sensecap, rak, helium hotspot details
**How**
fix up helium-hardware-definitions and pull in the new versions
**References**
https://github.com/NebraLtd/helium-hardware-definitions/releases/tag/v0.1.6a3

bump sensecap, rak, helium hotspot details

---

README.md
files/configurePktFwd.py
lora_templates_sx1301/EU433-global_conf.json
lora_templates_sx1302/EU433-global_conf.json

**Why**
add support for eu433 region
**How**
- add eu433 support in packet forwarder config for sx1301 and sx1302
**References**
Closes: #18

freq: add EU433 support

---

lora_templates_sx1301/AS923-1-global_conf.json
lora_templates_sx1301/AS923-2-global_conf.json
lora_templates_sx1301/AS923-3-global_conf.json
lora_templates_sx1301/AS923-4-global_conf.json
lora_templates_sx1301/KR-global_conf.json

Remove listen before talk
Closes: #53
**Why**
**How**
**References**

Remove listen before talk

---

.github/pull_request_template.md

**Why**
We are setting up a new PR template 
**How**
Applied new PR template to PR file
**References**
[Issue 23](https://github.com/NebraLtd/product-management/issues/23)

feat: New PR Template

---

Dockerfile

**Issue**
- Link: https://github.com/NebraLtd/packet_forwarder/pull/4
- Summary: pocv11 broke things
**How**
bump packet forwarder version
**References**
https://github.com/NebraLtd/packet_forwarder/pull/4
**Checklist**

fix: bump packet forwarder version

---

requirements.txt

bump hm-pyhelper
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

bump hm-pyhelper

---

requirements.txt

add finestra variant
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

bump pyhelper to add finestra

---

requirements.txt

fix pin mapping on helium og
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

feat: bump pyhelper for helium og update

---

requirements.txt

**Issue**
NebraLtd/helium-miner-software#465
**Checklist**

Bumped hm-pyhelper to fix Cotx I2C addr issue

---

Dockerfile
requirements.txt

**Issue**
- Link:
- Summary: bump base images and update requirements
**How**
- bump base images to bookworm-20221215
- bump requirements.txt to latest versions
**References**
**Checklist**

feat: bump base images and update requirements

---

Dockerfile
requirements.txt

Bookworm is still in testing phase so better to move to bullseye instead
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

fix: revert to bullseye

---

pktfwd/config/lora_templates_sx1301/global_conf.json.AS923_1A
pktfwd/config/lora_templates_sx1301/global_conf.json.AS923_1B
pktfwd/config/lora_templates_sx1301/global_conf.json.AS923_2A
pktfwd/config/lora_templates_sx1301/global_conf.json.AS923_3A
pktfwd/config/lora_templates_sx1301/global_conf.json.AS923_4A
pktfwd/config/lora_templates_sx1301/global_conf.json.AU915_SB2
pktfwd/config/lora_templates_sx1301/global_conf.json.CN470_A
pktfwd/config/lora_templates_sx1301/global_conf.json.EU433
pktfwd/config/lora_templates_sx1301/global_conf.json.EU868_A
pktfwd/config/lora_templates_sx1301/global_conf.json.IN865_A
pktfwd/config/lora_templates_sx1301/global_conf.json.KR920_A
pktfwd/config/lora_templates_sx1301/global_conf.json.RU864_A
pktfwd/config/lora_templates_sx1301/global_conf.json.US915_SB2
pktfwd/config/lora_templates_sx1301/local_conf.json
pktfwd/config/lora_templates_sx1302/global_conf.json.AS923_1A
pktfwd/config/lora_templates_sx1302/global_conf.json.AS923_2A
pktfwd/config/lora_templates_sx1302/global_conf.json.AS923_3A
pktfwd/config/lora_templates_sx1302/global_conf.json.AS923_4A
pktfwd/config/lora_templates_sx1302/global_conf.json.AU915_SB2
pktfwd/config/lora_templates_sx1302/global_conf.json.CN470_A
pktfwd/config/lora_templates_sx1302/global_conf.json.EU433
pktfwd/config/lora_templates_sx1302/global_conf.json.EU868_A
pktfwd/config/lora_templates_sx1302/global_conf.json.IN865_A
pktfwd/config/lora_templates_sx1302/global_conf.json.KR920_A
pktfwd/config/lora_templates_sx1302/global_conf.json.RU864_A
pktfwd/config/lora_templates_sx1302/global_conf.json.US915_SB2
pktfwd/config/lora_templates_sx1302/local_conf.json

Switched packet forwarder to send packets to multiplexer...
Concentrator -> Packetforwarder -> Multiplexer -> Helium Miner
Only merge https://github.com/NebraLtd/helium-miner-software/pull/602 after this merge.

FEAT: Switch packet forwarder to use multiplexer

---

Dockerfile
setenv_pktfwd.sh
start_pktfwd.sh

Made the repo aware of the injected production files

---

pktfwd/config/lora_templates_sx1301/local_conf.json
pktfwd/config/lora_templates_sx1302/local_conf.json
pktfwd/utils.py
requirements.txt

Accompanies https://github.com/NebraLtd/hm-pktmux/pull/2 - must be merged together.
- Sets Gateway EUI based on mac address of Ethernet if available or WiFi.
- Required for ThingsIX / TTN etc...

FEAT: Populate local conf file with Gateway EUI at runtime

---

.github/workflows/compile-docker.yml
.github/workflows/linter.yml
.github/workflows/security-audit.yml
.github/workflows/shellcheck.yml
Dockerfile

**Issue**
- Link: https://github.com/NebraLtd/helium-rak/issues/19
- Summary: feat: build using multiple base image architectures
**How**
- build using raspberry-pi and raspberrypi3-64 base images
- push to docker hub with multi-arch variants
- bumped versions of actions in repo
**References**
Relates-to: https://github.com/NebraLtd/helium-rak/issues/19
Relates-to: https://github.com/NebraLtd/helium-controllino/issues/5
**Checklist**

feat: build using multiple base image architectures

---

.github/workflows/compile-docker.yml
Dockerfile

Add amd64 variant
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

feat: add amd64 variant

---

pktfwd/config/lora_templates_sx1301/local_conf.json
pktfwd/config/lora_templates_sx1302/local_conf.json

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Revert to direct to Helium miner for now.

---

pktfwd/config/lora_templates_sx1302/global_conf.json.AS923_1A
pktfwd/config/lora_templates_sx1302/global_conf.json.AS923_1B
pktfwd/config/lora_templates_sx1302/global_conf.json.AS923_2A
pktfwd/config/lora_templates_sx1302/global_conf.json.AS923_3A
pktfwd/config/lora_templates_sx1302/global_conf.json.AS923_4A
pktfwd/config/lora_templates_sx1302/global_conf.json.AU915_SB2
pktfwd/config/lora_templates_sx1302/global_conf.json.CN470_A
pktfwd/config/lora_templates_sx1302/global_conf.json.EU433
pktfwd/config/lora_templates_sx1302/global_conf.json.EU868_A
pktfwd/config/lora_templates_sx1302/global_conf.json.IN865_A
pktfwd/config/lora_templates_sx1302/global_conf.json.KR920_A
pktfwd/config/lora_templates_sx1302/global_conf.json.RU864_A
pktfwd/config/lora_templates_sx1302/global_conf.json.US915_SB2
pktfwd/config/lora_templates_sx1302/local_conf.json
pktfwd/utils.py

combine local and global conf for sx1302
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

feat: combine local and global conf for sx1302

---

.github/workflows/compile-docker.yml
Dockerfile
requirements.txt

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Bump pyhelper

---

requirements.txt

bump hm-pyhelper to v0.14.9
Closes: #140
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

fix: bump hm-pyhelper

---

.github/workflows/compile-docker.yml

**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**

Fix manifest issue
